# Need docker
sudo: required
services:
  - docker

# Steps to do before test
before_install:
  - cd apps/react-app/
  - docker build -t react-app-test -f Dockerfile.dev .

# Commands required for test
script:
  - docker run -e CI=true react-app-test npm run test

# Commands to deploy
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-381217795047"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 

