# Need docker
sudo: required
services:
  - docker

# Steps to do before test
before_install:
  - cd apps/react-app/
  - docker build -t react-app-test -f Dockerfile.dev .

# Commands required for test
script:
  - docker run react-app-test npm run test -- --coverage
